### PR TITLE
Minor syntax/dependency changes

### PR DESCRIPTION
**Pull request by joheenc**
-added missing 'end' in pointsify
-fixed keyword argument syntax errors in optimal_periods, periodogram, and flatten
-added export pointsify, flatten, scrambled_periodogram, movingstd
-added using Optim

### CODE REVIEW

**Comment by ajwheeler** [comment]
What version of Julia are you using?  That should be the correct syntax for default values.  E.g. `optimal_periods` (which should probably be named something else, maybe `loguniform_grid`), can be called as 

    optimal_periods()
    optimal_periods(5)
    optimal_periods(5, 50)
    optimal_periods(5, 50, n=6)
    optimal_periods(n=6)

but not as
    
    optimal_periods(pmin=5)

because that isn't a keyword argument.

Anyway, this isn't a huge deal, since the keyword syntax is also fine, but I think for some methods the default value syntax is cleaner.

What do you think?  You probably have more insight than me into what is confusing, since I wrote the code.

**Comment by joheenc** [comment]
I'm on Julia 0.6.4.
My bad, I thought it was keyword argument syntax because in the sample code given the readme it was called like optimal_periods(pmin=0.25, pmax=50). Yeah, I agree that it's clearer with the default value syntax

**Comment by ajwheeler** [comment]
Just fixed the README.  Thanks.

**Comment by ajwheeler** [comment]
Did you introduce a typo at the end of pointsify? 
end -> endop 
?

**Comment by joheenc** [comment]
Yeah my bad lol I fixed it in the next commit

**Pull request merged**
